### PR TITLE
Fix panic at double-width leaf cell_at called

### PR DESCRIPTION
**Pull request by llwwns**
https://github.com/vhakulinen/gnvim/pull/102#issuecomment-526799751

### CODE REVIEW

**Comment by vhakulinen** [comment]
Add a test case covering this. Also, can you provide a (real) case where this breaks?

**Comment by llwwns** [comment]
I find a way to make the panic happen.

1. Use this init.vim
```
set runtimepath+=~/.vim
call plug#begin('~/.vim/plugged')
Plug 'tyru/eskk.vim'
call plug#end()
```
eskk.vim is a Japanese IME written in vimscript.

2. Run
```
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

3. Run neovim and execute `Plug Install`

4. Rerun neovim and type <c-j>A<c-j>

**Comment by smolck** [comment]
@vhakulinen Now that this is merged, I believe #117 and #92 should now be fixed (they panicked at the `cell_at` call),

**Comment by vhakulinen** [comment]
Added comment there to wait for confirmation.

**Pull request merged**
