### PR TITLE
[WIP] Refactor redraw event parsing

### PR DESCRIPTION
**Pull request by smolck**
Beginning of refactor outlined in #77. Not ready for merging yet, will update when ready. For now, feel free to hack around, ask questions, and give suggestions (they are welcome and appreciated, especially for variable names and, of course, the implementation). ATM this will not run without crashing, but that should change as the refactor progresses (I think; not certain but I think it crashes due to certain events not being handled ATM). Note that I haven't updated the tests yet.

@vhakulinen Would you mind giving this a review when you get the chance, and let me know what needs changing before I proceed? I had to change a few things from your outline in #77; let me know what you think.

### CODE REVIEW

**Comment by vhakulinen** [comment]
Looking good so far. The `grid_clear` doesn't need a struct, it can be just a vector of integers.

**Comment by smolck** [comment]
@vhakulinen How much refactoring do you prefer I include per commit? I was going to do five redraw events each, but if you want it structured differently please let me know.

**Comment by badosu** [comment]
Great work @smolck :clap:

**Comment by smolck** [comment]
Thanks @badosu! (@vhakulinen deserves most of the credit though; I'm just following his guidelines.) If you have any suggestions/comments/criticisms/commits/etc., please let me know!

**Comment by smolck** [comment]
@vhakulinen ATM I've kept the parsing for the `flush`, `busy_start`, `busy_stop`, and `popupmenu_hide` events the same as they were previously. Wasn't sure if those need a refactor. If so, let me know how you want to do the refactor and I'll push the changes.

**Comment by smolck** [comment]
Now all that's left is the ui.rs refactor (and likely some polish). As an FYI, GNvim runs great (and better!) AFAIK with this branch (that is, when ui.rs is fixed locally). There are probably some things that I've missed with the nvim_bridge/* changes, so reviews, changes, etc. are welcome!

**Comment by vhakulinen** [comment]
Did some additions and merged.

**Pull request merged**
