### PR TITLE
Add --disable-ext-option command argument

### LINKED ISSUE #21: Feature request: Disable externalized cmdline
I was not able to find how to disable externalized cmdline.

If it's not supported I'd like to suggest providing an option for it.

### PR DESCRIPTION
**Pull request by badosu**
Fix #21

### CODE REVIEW

**Comment by agraven** [comment]
It would make sense to add a --displable-ext_tabline option as well.

**Comment by badosu** [comment]
@agraven Is this something you'd use?

**Comment by agraven** [comment]
Yep, right now I've just manually changed `src/main.rs:116` to `ui_opts.set_tabline_external(false);`

**Comment by badosu** [comment]
@agraven Let me know if it works for you

**Comment by agraven** [comment]
@badosu Yup, works as intended.

**Comment by vhakulinen** [comment]
Can you also add option to disable the popupmenu and change the flag format to be `--disable-ext-cmdline` (change the underscore to dash)?

**Comment by badosu** [comment]
Done

**Comment by vhakulinen** [comment]
thanks!

**Pull request merged**
