### PR TITLE
Wildmenu -> pmenu events MVP

### PR DESCRIPTION
**Pull request by vhakulinen**
Just throwing this here for now.

### CODE REVIEW

**Comment by smolck** [comment]
Should this be merged before we work on #57? (And if so, what further work needs to be done here, if any?)

**Comment by vhakulinen** [comment]
Maybe. This requires nvim 0.4.0 which is not released yet, while ext_messages API exists on version 0.3.

**Comment by bfredl** [comment]
`ext_messages` is on master only and not in 0.3.x

**Comment by vhakulinen** [comment]
Oh, that's right.

**Pull request closed without merging**
